// Main export for shared package
// Export types first, then validation schemas only

export * from './types/index.js';
export * from './replay/index.js';

// Validation schemas (exports only schemas and inferred types, not duplicates)
export {
  GuestUserSchema,
  GuestSessionSchema,
  AuthResponseSchema,
  RoomSchema,
  RoomParticipantSchema,
  PresenceSchema,
  RoomStateSchema,
  ViewportSchema,
  RoomParticipantStatusSchema,
  ObjectTypeSchema,
  TextObjectSchema,
  RectangleObjectSchema,
  CircleObjectSchema,
  StickyObjectSchema,
  ImageObjectSchema,
  AudioObjectSchema,
  VideoObjectSchema,
  CanvasObjectSchema,
  CanvasObjectPatchSchema,
  CanvasSnapshotSchema,
  ErrorResponseSchema,
  AckResponseSchema,
  RoomCreatePayloadSchema,
  RoomCreatedPayloadSchema,
  RoomJoinPayloadSchema,
  RoomStateSnapshotPayloadSchema,
  RoomLeavePayloadSchema,
  RoomUserJoinedPayloadSchema,
  RoomUserLeftPayloadSchema,
  PresenceUpdatePayloadSchema,
  PresenceUpdatedPayloadSchema,
  CursorUpdatePayloadSchema,
  CursorUpdatedPayloadSchema,
  ObjectCreatePayloadSchema,
  ObjectCreatedPayloadSchema,
  ObjectUpdatePayloadSchema,
  ObjectUpdatedPayloadSchema,
  ObjectDeletePayloadSchema,
  ObjectDeletedPayloadSchema,
  BulkSyncRequestPayloadSchema,
  SyncDeltaBatchPayloadSchema,
  MediaRegisterPayloadSchema,
  SyncErrorPayloadSchema,
  RoomEventTypeSchema,
  RoomEventSchema,
  RoomEventsListRequestSchema,
  RoomEventsListResponseSchema,
} from './validation/index.js';
